# -*- coding: utf-8 -*-
"""projectOrange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAK0IPJFtF83i2cea2RzZSt74jITdDzT
"""

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
from google.colab.patches import cv2_imshow

def getContours(img):
  contours, hierarchy = cv.findContours(img, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE)
  for cnt in contours:
    area = cv.contourArea(cnt)
    print(area)
    if area > 20:
      cv.drawContours(imgCountour, cnt, -1, (255, 0, 0), 3)
      peri = cv.arcLength(cnt, True)
      # print(peri)
      #aqui pode-se filtrar a imagem para remover os edges dos contornos
      approx = cv.approxPolyDP(cnt, 0.02*peri, True)
      print(len(approx))
      objCorner = len(approx)
      x, y, w, h = cv.boundingRect(approx)
      if objCorner == 3: objectType = "Tri"
      elif objCorner == 4:
        aspRatio = w/float(h)
        if aspRatio > 0.95 and aspRatio < 1.05: objectType = "Square"
        else: objectType = "Rectangle"
      elif objCorner > 4: objectType = "Circle"
      else: objectType = "None"
      
      cv.rectangle(imgCountour,(x,y),(x+w, y+h), (0,255,0), 2)
      cv.putText(imgCountour, objectType,(x+(w//2)-10,y+(h//2)-10), cv.FONT_HERSHEY_COMPLEX, 0.7,(0,0,0),2)



img = cv.imread('./laranjeira_15.jpg')
cv2_imshow(img)

hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)
#cv2_imshow(hsv)

lower = np.array([1, 50, 120])
upper = np.array([25, 255, 255])

mask = cv.inRange(hsv, lower, upper)
cv2_imshow(mask)

masked = cv.bitwise_and(img, img, mask=mask)
cv2_imshow(masked)

canny = cv.Canny(mask, 150, 175)
print('Canny')
cv2_imshow(canny)

#Contours
"""
blank = np.zeros(img.shape, dtype='uint8')
contours, hierarchies = cv.findContours(canny, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)} contour(s) found!')
cv.drawContours(blank, contours, -1, (0,0,255), 1)
cv2_imshow(blank)
"""


imgCountour = masked.copy()
getContours(canny)
cv2_imshow(imgCountour)


cv.waitKey(0)